#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "animarr"
name = "Animarr"
description.en = "Smart Torznab proxy for Anime metadata resolution"
description.fr = "Proxy Torznab intelligent pour la résolution de métadonnées d'Anime"

version = "1.2.7~ynh1"
maintainers = ["wiwileborne"]

[upstream]
license = "MIT"
code = "https://github.com/wiwileborne/Animarr"

[integration]
yunohost = ">= 11.0"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "100M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/animarr"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]
    [resources.system_user]
    
    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5000

    [resources.sources.main]
    # Architecture detection handled by YunoHost
    amd64.url = "https://github.com/wiwileborne/Animarr/releases/download/v1.2.7/animarr-linux-x64.zip"
    amd64.sha256 = "7eeed46e0aca4af8ac2c278e865580c6383f3ac7a693b4cd2992d4a12d5fd5f5"
    arm64.url = "https://github.com/wiwileborne/Animarr/releases/download/v1.2.7/animarr-linux-arm64.zip"
    arm64.sha256 = "19d3c75f9e6c940e7d28f8a9caf425f989496182dc6e47c7e0cd11d256b9e35a"
    # The zip contains a 'release' folder, so we skip 1 level
    in_subdir = 1
