# sub_path_only for upstream
location __PATH__/ {

    # If you want to use YunoHost SSO to protect the app
    # (Leaving ADMIN_PASSWORD empty in .env will delegate auth to this)
    # include conf.d/yunohost_panel.conf.inc;

    proxy_pass http://localhost:__PORT__/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Support for WebSockets (if needed in the future)
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Increase timeout for long API calls
    proxy_read_timeout 300s;
    proxy_connect_timeout 75s;
}
