#!/bin/bash

# Load YunoHost helper
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

# Remove nginx config
ynh_config_remove_nginx

# Remove systemd config
ynh_config_remove_systemd

# Remove app directory (using standard path)
ynh_secure_remove "/var/www/$app"

# Note: We keep /var/lib/$app (data) as per YunoHost policy
# Unless the user explicitly wants to purge everything.
